import { ApplicationConfig, importProvidersFrom } from '@angular/core';
import { provideRouter } from '@angular/router';
import { routes } from './app.routes';
import { provideHttpClient } from '@angular/common/http';
import { provideMarkdown } from 'ngx-markdown';
import {
  LucideAngularModule,
  AlertCircle,
  Flame,
  RefreshCw,
  Clock,
  TrendingUp,
  CheckCircle2,
  Circle,
  Play,
  Map,
  Users,
  Compass,
  LayoutDashboard,
  BookOpen,
  User,
  LogOut,
  X,
  CheckCircle,
  Info,
  ArrowLeft,
  ArrowRight,
  Brain,
  Youtube,
  FileText,
  Share2,
  NotebookPen,
  Mail,
  Edit3,
  Calendar,
  Award,
  Target,
  Sparkles,
  Globe,
  Lock,
  Bell,
  Github,
  ChevronRight,
  Heart,
  Plus,
} from 'lucide-angular';

export const appConfig: ApplicationConfig = {
  providers: [
    provideRouter(routes),
    provideHttpClient(),
    provideMarkdown(),
    importProvidersFrom(
      LucideAngularModule.pick({
        AlertCircle,
        Flame,
        RefreshCw,
        Clock,
        TrendingUp,
        CheckCircle2,
        Circle,
        Play,
        Map,
        Users,
        Compass,
        LayoutDashboard,
        BookOpen,
        User,
        LogOut,
        X,
        CheckCircle,
        Info,
        ArrowLeft,
        ArrowRight,
        Brain,
        Youtube,
        FileText,
        Share2,
        Globe,
        Lock,
        NotebookPen,
        Target,
        ChevronRight,
        Plus,
        Sparkles,
        Mail,
        Edit3,
        Calendar,
        Award,
        Bell,
        Github,
        Heart,
      }),
    ),
  ],
};
